# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOPc76ZyXXYkMpG4OYHvYjAiOADekpHg
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

import io
df = pd.read_csv(io.BytesIO(uploaded['Dataset (1) - Sheet1 (1) (1).csv']))

df.head()

df.shape

dataPatient50andAbove = df[df.Age > 50]

dataPatient50andAbove

dataPatient50andAbove.head()

dfFee700andAbove = df[df.Fee > 700]

dfFee700andAbove

!pip install torch

!pip install torchvision

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

df.describe()

import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

sns.lmplot(x='Age' ,y='Cholesterol Level', data=df)